### ISSUE TITLE
Not able to retrieve topic submit key in case of threshold key [TopicID 0.0.161739]

### ISSUE THREAD

**Issue by bakasura980** [hashgraph/hedera-sdk-go#112] opened 2020-12-18 13:35 UTC
My team faced a problem while playing with the threshold keys

Issue:
We can set a key list with a threshold as a submit key of a topic. One of our tasks is to obtain all the public keys from the threshold one. When we try to do that by getting the topic info, the submit key is always an empty one, although we have correctly set it on the topic’s creation

**Comment by gregscullard** [comment] 2020-12-18 15:31
Looks like the issue is deeper than just `topicInfo`.

In `consensus_topic_create_transaction.go`, the parameter for `SetAdminKey` and `SetSubmitKey` is `PublicKey` which won't allow for a key list or threshold key (in comparison, `account_create_transaction.SetKey` takes a `Key`

That probably needs fixing first

Then, `topic_info.go`:
```
AdminKey           *PublicKey
SubmitKey          *PublicKey
```

likely should be 

```
AdminKey           Key
SubmitKey          Key
```

which matches `accountInfo.go`

**Comment by andrix10** [comment] 2020-12-21 23:02
Thanks for bringing this up, I fixed this and should be available in the next patch.

**Comment by bakasura980** [comment] 2020-12-22 12:57
@andrix10 , the best! Really appreciate that

**Comment by danielakhterov** [comment] 2021-03-27 00:18
Staling issue; closing. @bakasura980 if you're having further issues please re-open.

**Closed by danielakhterov** 2021-03-27 00:18 UTC
