### ISSUE TITLE
Investigate `INVALID_NODE_ACCOUNT`

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-go#425] opened 2022-03-04 18:14 UTC
### Description

Around 5% of transactions experienced INVALID_NODE_ACCOUNT error.

When running a transaction that minted approximately 100 NFTs, we received these 5 errors:

```
exceptional precheck status INVALID_NODE_ACCOUNT received for transaction 0.0.727040@1646251530.242082165
exceptional precheck status INVALID_NODE_ACCOUNT received for transaction 0.0.727040@1646251544.254671924
exceptional precheck status INVALID_NODE_ACCOUNT received for transaction 0.0.727040@1646251559.35754613
exceptional precheck status INVALID_NODE_ACCOUNT received for transaction 0.0.727040@1646251571.725229734
exceptional precheck status INVALID_NODE_ACCOUNT received for transaction 0.0.727040@1646251583.871463536
exceptional precheck status INVALID_NODE_ACCOUNT received for transaction 0.0.727040@1646251590.900184413
exceptional precheck status INVALID_NODE_ACCOUNT received for transaction 0.0.727040@1646251590.588439607
```

### Steps to reproduce

```
mintTx, err := hedera.NewTokenMintTransaction().
        SetTokenID(tokenId).
        SetMetadata([]byte(CID)).
        FreezeWith(client)

    if err != nil {
        handle error
    }
    //Sign the transaction with the supply key
    mintTxSign := mintTx.Sign(supplyKey)

    //Submit the transaction to a Hedera network
    mintTxSubmit, err := mintTxSign.Execute(client)
    if err != nil {
         handle error
    }

    //Get the transaction receipt
    mintRx, err := mintTxSubmit.GetReceipt(client)
    if err != nil {
           handle error
    }
    //print the token and serial numbers
    fmt.Println( Minted TOKEN", tokenId, "with serial:", mintRx.SerialNumbers)
```

### Hedera network

mainnet
### Version

[github.com/hashgraph/hedera-sdk-go/v2](http://github.com/hashgraph/hedera-sdk-go/v2) v2.9.0
[github.com/hashgraph/hedera-protobufs-go](http://github.com/hashgraph/hedera-protobufs-go) v0.2.1-0.20220129033520-fdf6f206e34e // indirect
go 1.17.6

**Comment by SimiHunjan** [comment] 2022-03-04 21:36
Already regenerate transactions on retry with signatures and node account IDs on demand. 

Will continue to investigate the reason for this error.

**Comment by monkeyboy1492** [comment] 2022-03-05 00:26
This occurred on MAINNET in production,  not TestNet

**Comment by Ljzn** [comment] 2022-03-20 10:06
We got this error too. About 1 in 6 transactions.

**Comment by Ljzn** [comment] 2022-03-21 07:40
we investigated the failed transactions, found they all transmitted with node 0.0.25. This info may help.

**Comment by monkeyboy1492** [comment] 2022-04-04 23:08
Closed? Why? There has been no resolution nor any workaround?
What is the root cause? Telling us node 0.0.25 means nothing...
Has this node been repaired? Do we need to programmatically NOT use this node? (and if so - please provide sample code)
How do we know this will not happen again in the future? perhaps on another node?
What is the correct way to handle this error?

I am sorry, but simply closing the error does not give us the comfort to continue to use this in production.
Please clarify the root cause, the solution, and any change in handling required on the client end.

Thank-you

**Comment by SimiHunjan** [comment] 2022-04-04 23:10
hi @monkeyboy1492 - this issue was noted as resolved by @andrix10 . @andrix10 could you please provide the reference for this issue?

**Comment by andrix10** [comment] 2022-04-05 02:48
We released a fix for this in the last beta release, and so far I have no been getting the error during any of my testing. For avoiding the node if you don't explicitly set a node it will pick a random not from healthy list, if a node is unhealthy it will be removed from the list and therefore it shouldn't fail if one or two nodes are down. If you are still experiencing this error, we can reopen this issue,

**Comment by andrix10** [comment] 2022-09-09 07:54
I put that code on a loop, and in 30 or so runs it didn't error once for me. Was it in mainnet?

**Comment by edmundrotimi** [comment] 2022-09-10 12:54
The error was in testnet.

**Comment by danielakhterov** [comment] 2022-10-04 02:13
https://github.com/hashgraph/hedera-sdk-go/issues/569#issuecomment-1266300411
Hey guys, I know it's really discouraging and annoying for us to open and close this issue several times, but it's just hard to reproduce this issue and hence hard to confirm an expected fix worked. Nonetheless, I'm going to have to do that one more time here as I _think_ we've resolved this in the last releases. 
Note, you may still hit this error in version <=2.17.4 but if you hit this issue >=2.17.5 then we'll need to re-open this issue as the expected fix did not work.

**Closed by danielakhterov** 2022-10-04 02:13 UTC
Labels: bug, p1
