### ISSUE TITLE
v2.1.0 Token info query errors

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-go#105] opened 2020-12-02 05:42 UTC
```
	//Create the query
	query := hedera.NewTokenInfoQuery().
		SetTokenID(tokenId)

	//Sign with the client operator private key and submit to a Hedera network
	tokenInfo, err := query.Execute(client)

	if err != nil {
		panic(err)
	}

	fmt.Printf("The token info %v\n", tokenInfo)
```

Error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x14470eb]

goroutine 1 [running]:
github.com/hashgraph/hedera-sdk-go.tokenInfoFromProtobuf(0xc000464000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/simihunjan/Desktop/hedera-sdk-go-2.1.0/token_info.go:141 +0x52b
github.com/hashgraph/hedera-sdk-go.(*TokenInfoQuery).Execute(0xc000334960, 0xc00010ed70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/simihunjan/Desktop/hedera-sdk-go-2.1.0/token_info_query.go:142 +0x34d
main.main()
        /Users/simihunjan/Desktop/hedera-sdk-go-2.1.0/examples/tokens/main.go:234 +0x25b5
exit status 2

```

**Comment by danielakhterov** [comment] 2020-12-30 04:40
I believe this was caused by us expecting certain keys to not be nullable. Since then this has been fixed on master, and will be available on next release. If you're having further trouble please reopen this issue.

**Closed by danielakhterov** 2020-12-30 04:40 UTC
