### ISSUE TITLE
INVALID_NODE_ACCOUNT

### ISSUE THREAD

**Issue by edmundrotimi** [hashgraph/hedera-sdk-go#569] opened 2022-09-10 08:04 UTC
### Description

Hello, I am creating a Hedera dapp in Go; I get the error " INVALID_NODE_ACCOUNT received for the transaction 0.0.47705948@1662389461.396792890" each time I try to create an account.

### Steps to reproduce

1. using the create account example
2. use go latest version
3. run the program

### Hedera network

testnet

### Version

v2.17.2

### Operating system

Windows

**Comment by andrix10** [comment] 2022-09-13 07:25
Hello, I tried to reproduce the error but i can't get it. I ran it on loop for some time without setting node and it didn't error out. This was on testnet.

**Comment by edmundrotimi** [comment] 2022-09-14 06:36
I tested it again but I am not getting the error again. I really can not not explain why the error is not displaying.  Why does this error occur and how can I prevent it in the future.

**Comment by andrix10** [comment] 2022-09-16 04:27
Sorry for late reply, but I think it was some nodes down or under maintenance. Possibly outdated node ips, which the next update should fix.

**Comment by rokn** [comment] 2022-09-20 11:31
I've pinpointed this to this IP-s:
```
	"34.87.150.174:50211":   {Account: 25},
	"13.228.103.14:50211":   {Account: 25},
```
Glad to hear it's already in progress.

**Comment by danielakhterov** [comment] 2022-10-04 02:04
@edmundrotimi @rokn Going to close this issue as @andrix10 couldn't reproduce, and because I think the issue was our hard coded address book for mainnet was incorrect. However, we no longer hard code a mainnet address book, and instead we pull one from Hedera's official mirror node, so I don't think this issue should happen again unless it is an issue with the SDK or if the Hedera's official mirror node is returning invalid data (which I don't think it is). Until then we'll keep this issue closed. 

As a work around if you're not using or cannot use the latest SDK add the following to your client creation.
```go
var mainnetNodes = map[string]AccountID{
	"35.237.200.180:50211":  {Account: 3},
	"34.239.82.6:50211":     {Account: 3},
	"13.82.40.153:50211":    {Account: 3},
	"13.124.142.126:50211":  {Account: 3},
	"15.164.44.66:50211":    {Account: 3},
	"15.165.118.251:50211":  {Account: 3},
	"35.186.191.247:50211":  {Account: 4},
	"3.130.52.236:50211":    {Account: 4},
	"137.116.36.18:50211":   {Account: 4},
	"35.192.2.25:50211":     {Account: 5},
	"3.18.18.254:50211":     {Account: 5},
	"104.43.194.202:50211":  {Account: 5},
	"23.111.186.250:50211":  {Account: 5},
	"74.50.117.35:50211":    {Account: 5},
	"107.155.64.98:50211":   {Account: 5},
	"35.199.161.108:50211":  {Account: 6},
	"13.52.108.243:50211":   {Account: 6},
	"13.64.151.232:50211":   {Account: 6},
	"13.235.15.32:50211":    {Account: 6},
	"104.211.205.124:50211": {Account: 6},
	"13.71.90.154:50211":    {Account: 6},
	"35.203.82.240:50211":   {Account: 7},
	"3.114.54.4:50211":      {Account: 7},
	"23.102.74.34:50211":    {Account: 7},
	"35.236.5.219:50211":    {Account: 8},
	"35.183.66.150:50211":   {Account: 8},
	"23.96.185.18:50211":    {Account: 8},
	"35.197.192.225:50211":  {Account: 9},
	"35.181.158.250:50211":  {Account: 9},
	"23.97.237.125:50211":   {Account: 9},
	"31.214.8.131:50211":    {Account: 9},
	"35.242.233.154:50211":  {Account: 10},
	"3.248.27.48:50211":     {Account: 10},
	"65.52.68.254:50211":    {Account: 10},
	"179.190.33.184:50211":  {Account: 10},
	"35.240.118.96:50211":   {Account: 11},
	"13.53.119.185:50211":   {Account: 11},
	"23.97.247.27:50211":    {Account: 11},
	"35.204.86.32:50211":    {Account: 12},
	"35.177.162.180:50211":  {Account: 12},
	"51.140.102.228:50211":  {Account: 12},
	"35.234.132.107:50211":  {Account: 13},
	"34.215.192.104:50211":  {Account: 13},
	"13.77.158.252:50211":   {Account: 13},
	"35.236.2.27:50211":     {Account: 14},
	"52.8.21.141:50211":     {Account: 14},
	"40.114.107.85:50211":   {Account: 14},
	"35.228.11.53:50211":    {Account: 15},
	"3.121.238.26:50211":    {Account: 15},
	"40.89.139.247:50211":   {Account: 15},
	"34.91.181.183:50211":   {Account: 16},
	"18.157.223.230:50211":  {Account: 16},
	"13.69.120.73:50211":    {Account: 16},
	"34.86.212.247:50211":   {Account: 17},
	"18.232.251.19:50211":   {Account: 17},
	"40.114.92.39:50211":    {Account: 17},
	"172.105.247.67:50211":  {Account: 18},
	"172.104.150.132:50211": {Account: 18},
	"139.162.156.222:50211": {Account: 18},
	"34.89.87.138:50211":    {Account: 19},
	"18.168.4.59:50211":     {Account: 19},
	"51.140.43.81:50211":    {Account: 19},
	"13.246.51.42:50211":    {Account: 19},
	"13.244.166.210:50211":  {Account: 19},
	"34.82.78.255:50211":    {Account: 20},
	"13.77.151.212:50211":   {Account: 20},
	"34.76.140.109:50211":   {Account: 21},
	"13.36.123.209:50211":   {Account: 21},
	"34.64.141.166:50211":   {Account: 22},
	"52.78.202.34:50211":    {Account: 22},
	"35.232.244.145:50211":  {Account: 23},
	"3.18.91.176:50211":     {Account: 23},
	"34.89.103.38:50211":    {Account: 24},
	"18.135.7.211:50211":    {Account: 24},
	"34.93.112.7:50211":     {Account: 25},
	"13.232.240.207:50211":  {Account: 25},
	"34.87.150.174:50211":   {Account: 26},
	"13.228.103.14:50211":   {Account: 26},
	"34.125.200.96:50211":   {Account: 27},
	"13.56.4.96:50211":      {Account: 27},
	"35.198.220.75:50211":   {Account: 28},
	"18.139.47.5:50211":     {Account: 28},
}
client.SetNetwork(mainnetNodes)
```

**Closed by danielakhterov** 2022-10-04 02:04 UTC
Labels: bug
