### ISSUE TITLE
CryptoTransfer err when using go programming

### ISSUE THREAD

**Issue by goldenchain03** [hashgraph/hedera-sdk-go#11] opened 2018-12-04 10:11 UTC
The fragment of code giving the error (output shown later):
	fmt.Printf("Other account balance: %v \n", balance/1000000000)

	time.Sleep(1 * time.Second)

	// Start a Transaction
	// myAccount := hedera.AccountID{Account: 1001}
	// Get the operator Secret key id for sending a transaction to the network
	// This is the personal section of the key pair
	operatorSecret, err := hedera.SecretKeyFromString("<secret code string>")
	if err != nil {
		panic(err)
	}

	// The actual transaction that needs opearator account id,
	// node id onto which the transaction is submitted, what is the nature
	// of the transaction, and signing to authorise the transaction twice
	// Once as a operator, and another for participating in the network.
	response, err := client.CryptoTransfer().
		Operator(myAccount).
		Node(myAccount).
		Transfer(myAccount, 0).
		Transfer(myAccount, 0).
		Sign(operatorSecret).
		Sign(operatorSecret).
		Execute()

	if err != nil {
		panic(err)
	}

	os.Exit(3)

--------------------- 
go run main.go
Your balance: 100
Other account balance: 100
thread '<unnamed>' panicked at 'index 2495032638019500384 out of range for slice of length 128', src\libcore\slice\mod.rs:2349:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
exit status 3221225501

**Comment by mehcode** [comment] 2018-12-04 15:04
Please add your `go.sum` file (just the line that mentions hedera-sdk-go is enough), your operating system, and your architecture.

**Comment by goldenchain03** [comment] 2018-12-04 15:24
I ran
% go get github.com/hashgraph/hedera-sdk-go

My OS windows 10, Intel core i7

**Comment by goldenchain03** [comment] 2018-12-04 15:31
I created a directory and coded the main.go looking at Ken's U-tube video and fixing things as I went along. I am new to go and did not yet setup gitbhub repo or anything and not yet sure on go.mod and go.sum requirements.

**Comment by mehcode** [comment] 2018-12-04 15:43
Can you run `go get -u github.com/hashgraph/hedera-sdk-go` to ensure you're on the latest version?

`go.sum` is a lockfile that will pin the versions of your dependencies for reproducible builds. To generate an initial `go.mod` you can run `go mod init project-name`. From then on, `go get` will affect the local `go.mod` and `go.sum` instead of the whole system.

**Comment by goldenchain03** [comment] 2018-12-05 13:09
You mean I should run go mod init github.com/hashgraph/hedera-sdk-go
or go mod init <my local project name>?

**Comment by mehcode** [comment] 2018-12-05 16:29
See https://github.com/golang/go/wiki/Modules#quick-start-example

**Comment by BrainstemStudio** [comment] 2018-12-05 23:22
Running into the same issues:
"panicked at 'index 10714101903910392275 out of range for slice of length 128"

**go.mod:**
module Hedera
require github.com/hashgraph/hedera-sdk-go v0.0.0-20181129231644-85abb7694dac

**Environment:**
Windows 10
Intel core i7

**Comment by goldenchain03** [comment] 2018-12-06 01:14
go get -u github.com/hashgraph/hedera-sdk-go
# cd C:\CPATEL_DATA\Auroville\Aurinoco\Hedera\go_workspace\src\github.com\hashgraph\hedera-sdk-go; git pull --ff-only
error: Your local changes to the following files would be overwritten by merge:
        include/hedera-key.h
        key.go
        libs/x86_64-apple-darwin/libhedera.a
        libs/x86_64-pc-windows-gnu/hedera.lib
Please commit your changes or stash them before you merge.
Aborting
package github.com/hashgraph/hedera-sdk-go: exit status 1
-----------------------------


I have no changes opened in my source files. I did commit my files.
I don't know what does stash them or how to get around this.

I will look at the URL in the meanwhile.

**Comment by BrainstemStudio** [comment] 2018-12-06 09:04
@goldenchain03 
Looks like you have the hedera SDK in your project folder. Go should install the hedera SDK in a seperate folder or remote package. Take a look at the guideline on Go and packages https://golang.org/doc/code.html#remote

I would suggest starting a clean project and use VS Code as it comes with a lot of automation and helpers to assist with learning Go.  Try following these steps:

1. Open VS Code on your project folder e.g "go_workspace/src/github.com/<Your github account>/<your hedera project>/"

2. Open a new terminal in VS Code and type "go init mod <your project>". This will create a go.mod file.

3. Then type "go get -u github.com/hashgraph/hedera-sdk-go", this will create the go.sum file and modify your go.mod file with required dependencies.

3. Copy in your main.go keys.go files  (from your previous project) into your new project folder you don't need anything else.

The go.mod and go.sum are just project settings to remote dependencies, your main.go and keys.go should be the only things you need to worry about. Also do read the link above as it gives a standard on how your go projects and remote packages are structured in Go.

Hopes this helps.

**Comment by BrainstemStudio** [comment] 2018-12-06 09:12
Further insight into the "panicked at 'index ... out of range for slice of length 128" error. It appears to be invoked on the "Execute()" of a transaction and points to "src\libcore\slice\mod.rs:2349:5"

**Comment by goldenchain03** [comment] 2018-12-06 16:24
I followed the suggestion, recreated a fresh work setup.
Created the go mod init and go get -u u github.com/hashgraph/hedera-sdk-go

I am still getting the following error:
 go run main.go
Your balance: 100
Other account balance: 100
thread '<unnamed>' panicked at 'index 3701975637415471720 out of range for
slice of length 128', src\libcore\slice\mod.rs:2349:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
exit status 3221225501

**Comment by mehcode** [comment] 2018-12-07 04:17
Following up. I identified a couple places that may have caused that on Windows. v0.2 of the Go SDK should be out soon which will hopefully fix that.

**Comment by mehcode** [comment] 2018-12-07 09:55
@BrainstemStudio @goldenchain03 

Please update your go modules with `go get -u github.com/hashgraph/hedera-sdk-go`. 

v0.2 is out which seems to work flawlessly on my Windows 10 box. No breaking changes but we're making the builders more fluent so you'll see some deprecations flagged. Going to make a CHANGELOG soon

**Comment by BrainstemStudio** [comment] 2018-12-07 22:05
@mehcode Thanks can confirm it's working now.

**Comment by mehcode** [comment] 2018-12-07 22:15
Awesome 💯 

Closing this. Please re-open @goldenchain03 if you're still experiencing problems.

**Closed by mehcode** 2018-12-07 22:15 UTC
Labels: bug

**Comment by goldenchain03** [comment] 2018-12-08 15:50
// DEPRECATED -- balance, err := client.GetAccountBalance(myAccount).Answer()
	balance, err := client.Account(myAccount).Balance()

Has a runtime error
.\main.go:19:15: assignment mismatch: 2 variables but 1 values**
**

**Comment by mehcode** [comment] 2018-12-08 15:57
You still need to ask for the answer to the query. That's been renamed from `.Answer()` to `.Get()`.

**Comment by goldenchain03** [comment] 2018-12-09 05:58
response, err := client.TransferCrypto().
        Operator(myAccount).
        Node(myAccount).
        Transfer(myAccount, 0).
        Transfer(myAccount, 0).
        Sign(operatorSecret).
        Sign(operatorSecret).
        Execute()
    if err != nil {
        fmt.Printf("Exited after TransferCrypto\n")
        panic(err)
    }


panic: transaction failed the pre-check: InvalidTransaction

goroutine 1 [running]:
main.main()
exit status 2

**Comment by goldenchain03** [comment] 2018-12-09 05:59
balance = client.Account(otherAccount).Balance() // err?


What happened to err?
