### ISSUE TITLE
Various Hedera go sdk issues/inconsistencies found while working on wallet connect support

### ISSUE THREAD

**Issue by robkainz** [hashgraph/hedera-sdk-go#809] opened 2023-09-21 17:39 UTC
### Description

While working on a parser I need for all 36 transaction types to support wallet connect, I found a number of issues or inconsistencies. Rather than explain them all here, I have simply submitted unit tests in the attached files. It's possible you may disagree on whether or not a couple of these are defects.

The most important one that I need fixed for the Wallawallet wallet connect release is the one named TestHGoSdkIssue_Incorrectly_Throws_Unsupported_Transaction_Type_Error, where I cannot reconstitute an AccountUpdateTransaction from the transaction bytes. I have not yet attempted to debug this further than my own code.

[HederaSdkDefects_test.go.txt](https://github.com/hashgraph/hedera-sdk-go/files/12689544/HederaSdkDefects_test.go.txt)
[test-util.go.txt](https://github.com/hashgraph/hedera-sdk-go/files/12689545/test-util.go.txt)

I've included relevant portions of the output of running the tests below so you can see at a glance what the issues are:

```
Contents Base64:  
--- FAIL: TestHGoSdkIssue_FileAppendTransaction_Missing_Contents_After_Reconstitution (0.12s)
    HederaSdkDefects_test.go:86: error parsing transaction bytes: Expected to find Contents for FileAppendTransaction, but there were none.
Message Base64:  dGVzdCB0b3BpYyBtZXNzYWdl
Message Base64:  
--- FAIL: TestHGoSdkIssue_TopicMessageSubmitTransaction_Missing_Message_After_Reconstitution (0.12s)
    HederaSdkDefects_test.go:107: error parsing transaction bytes: Expected to find Contents for FileAppendTransaction, but there were none.
Assessment Method:  FeeAssessmentMethodInclusive
--- FAIL: TestHGoSdkIssue_CustomFractionFee_Missing_SetAssessmentMethod_Method (0.00s)
    HederaSdkDefects_test.go:116: There is currently no SetAssessmentMethod() for CustomFractionalFee in golang, but it exists in JS SDK and as far as I can tell is needed
--- FAIL: TestHGoSdkIssue_SystemDeleteTransaction_Type_Inconsistent_For_GetExpirationTime (0.09s)
    HederaSdkDefects_test.go:135: expected GetExpirationTime() to return a time.Time type (as that's what the setter uses), not: int64
--- FAIL: TestHGoSdkIssue_ContractCreateTransaction_Uses_Inconsistent_Type_For_MaxAutomaticTokenAssociations (0.10s)
    HederaSdkDefects_test.go:183: expected GetMaxAutomaticTokenAssociations() for AccountCreateTransaction and ContractCreateTransaction to return value of same type, but instead they were uint32 and int32
--- FAIL: TestHGoSdkIssue_AutoRenewAccount_Not_Correctly_Set_For_TokenCreateTransaction (0.10s)
    HederaSdkDefects_test.go:229: expected autoRenewAccount to be the one that was explictly set, which is 0.0.122837, but got 0.0.2240404
--- FAIL: TestHGoSdkIssue_TopicCreateTransaction_May_Be_Missing_expirationTime_Property (0.00s)
    HederaSdkDefects_test.go:251: The TopicCreateTransaction is missing the expirationTime property, yet the TopicUpdateTransaction has that property. This might be a bug.
FAIL
exit status 1

``` 

### Steps to reproduce

1. Rename the files to .go files
2. My project has just these dependencies: require (
	github.com/hashgraph/hedera-sdk-go/v2 v2.29.0
	github.com/stretchr/testify v1.8.4
	google.golang.org/protobuf v1.31.0
)
3. Once configured, just run "go test", or "go test -v -run <testname>" for an individual test.

### Hedera network

testnet

### Version

v2.29.0

### Operating system

macOS

**Comment by rokn** [comment] 2023-09-25 11:47
For `TestHGoSdkIssue_CustomFractionFee_Missing_SetAssessmentMethod_Method` there is actually a [SetAssessmentMethod](https://github.com/hashgraph/hedera-sdk-go/blob/develop/custom_fractional_fee.go#L119)

For `TestHGoSdkIssue_ContractCreateTransaction_Uses_Inconsistent_Type_For_MaxAutomaticTokenAssociations` This would require a bigger change in the API which is out of scope currently for us.

For `TestHGoSdkIssue_TopicCreateTransaction_May_Be_Missing_expirationTime_Property` that is by design, Hedera doesn't support setting the expiration time, you can only do it by updating the topic.

The other issues will be handled

**Comment by robkainz** [comment] 2023-09-25 19:39
I was quite sure I was using v2.29.0, but you are correct, the first two are passing now. I did a git fetch earlier today so perhaps I grabbed a newer version of that tag? I was also using an older SDK originally, v2.17.0 which I currently use in production for Wallawallet. Pretty sure SetAssessmentMethod() was missing there, but it does seem to be in the latest now. Thanks.

I have an additional question regarding account-allowance-delete-transaction.go. It seems like most every method in there is marked as deprecated, but without a replacement for those that appear in account-allowance-approve-transaction.go, except for the NFTs. Can you clarify? Is this a bug, or intended to create allowances for FTs/HBAR but not delete them?

**Comment by robkainz** [comment] 2023-09-26 14:41
And another serialization issue for TopicMemo for TopicCreateTransaction:

=== RUN   TestHGoSdkIssue_TopicCreateTransaction_Missing_TopicMemo_After_Reconstitution
b64Transaction: | CrYBKrMBCq4BChUKDAju2suoBhCt56O/AhIFGJTfiAESAhgEGICg2eYdIgMItAEyHXRlc3QgdG9waWMgdXBkYXRlIHRyYW5zYWN0aW9uwgFmCg90ZXN0IHRvcGljIG1lbW8SIhIgXYnw0+3YHV7hy4qouJFxw2YVddamRpqKM5qWDTALN5waIhIgXYnw0+3YHV7hy4qouJFxw2YVddamRpqKM5qWDTALN5wyBQiAnJw5OgQY1b8HEgAKtgEqswEKrgEKFQoMCO7ay6gGEK3no78CEgUYlN+IARICGAcYgKDZ5h0iAwi0ATIddGVzdCB0b3BpYyB1cGRhdGUgdHJhbnNhY3Rpb27CAWYKD3Rlc3QgdG9waWMgbWVtbxIiEiBdifDT7dgdXuHLiqi4kXHDZhV11qZGmoozmpYNMAs3nBoiEiBdifDT7dgdXuHLiqi4kXHDZhV11qZGmoozmpYNMAs3nDIFCICcnDk6BBjVvwcSAAq2ASqzAQquAQoVCgwI7trLqAYQreejvwISBRiU34gBEgIYAxiAoNnmHSIDCLQBMh10ZXN0IHRvcGljIHVwZGF0ZSB0cmFuc2FjdGlvbsIBZgoPdGVzdCB0b3BpYyBtZW1vEiISIF2J8NPt2B1e4cuKqLiRccNmFXXWpkaaijOalg0wCzecGiISIF2J8NPt2B1e4cuKqLiRccNmFXXWpkaaijOalg0wCzecMgUIgJycOToEGNW/BxIA |
    HederaSdkDefects_test.go:256: error parsing transaction bytes: Expected topic memo to be "test topic memo" but was ""
--- FAIL: TestHGoSdkIssue_TopicCreateTransaction_Missing_TopicMemo_After_Reconstitution (0.10s)

**Comment by rokn** [comment] 2023-09-27 08:36
The smart contract update bytecodeId field is actually deprecated in hedera services.
For the allowance, yes it also seems that currently Hedera supports deleting only NFT allowances

**Comment by robkainz** [comment] 2023-10-16 18:16
The getter return value type for the system_delete_transaction.go method GetExpirationTime() still returns an int64 while the setting accepts a time.Time type. This interface is inconsistent and was not addressed in the fixes or by your comments. Are you planning to address this?

**Comment by gregscullard** [comment] 2023-10-19 14:18
Reopening to ensure the team addresses the questions raised after the issue was closed.

**Comment by Petyo-Lukanov** [comment] 2023-12-20 12:10
Hi all, since there have been no new comments here, I will close this issue

**Closed by Petyo-Lukanov** 2023-12-20 12:10 UTC
Labels: bug
