### ISSUE TITLE
Panic inducing memory error in latest commit (a7e5213)

### ISSUE THREAD

**Issue by rhysied** [hashgraph/hedera-sdk-go#49] opened 2020-02-27 19:23 UTC
Hi,

Tried upgrading our test server to the newest version of the Go SDK (it was actually running a legacy version from earlier in January), and our application seemed to throw a panic which points to the proto library (see stack trace).

I checked out an earlier commit (ef4bb90) that I was using both locally and in our production setup and the issue disappeared. The stack trace mentions a call to GetCost which was introduced after this commit so not sure if that may be the source (or it may be a red herring).

Stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x967f59]

goroutine 1 [running]:
github.com/golang/protobuf/proto.makeOneOfMarshaler.func1(0xc0001e0e60, 0x0, 0x0)
	/var/lib/appuser/worker/go/src/github.com/golang/protobuf/proto/table_marshal.go:2373 +0x129
github.com/golang/protobuf/proto.(*marshalInfo).size(0xc0001e0e70, 0xc0001e0e00, 0xc000346060)
	/var/lib/appuser/worker/go/src/github.com/golang/protobuf/proto/table_marshal.go:183 +0x9d
github.com/golang/protobuf/proto.(*InternalMessageInfo).Size(0xc000346060, 0xe82500, 0xc0001e0e00, 0x0)
	/var/lib/appuser/worker/go/src/github.com/golang/protobuf/proto/table_marshal.go:125 +0x66
github.com/golang/protobuf/proto.Marshal(0xe82500, 0xc0001e0e00, 0x23f09, 0xbf8e0c202fa0a279, 0xfffffffdacd6ddee, 0x1378c80, 0xc00025a800)
	/var/lib/appuser/worker/go/src/github.com/golang/protobuf/proto/table_marshal.go:2727 +0xfe
github.com/hashgraph/hedera-sdk-go.TransactionBuilder.Build(0xc0001e0e00, 0xc000010200, 0xc00025a1c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/var/lib/appuser/worker/go/src/github.com/hashgraph/hedera-sdk-go/transaction_builder.go:52 +0x166
github.com/hashgraph/hedera-sdk-go.(*QueryBuilder).GetCost(0xc0001135a0, 0xc00025a1c0, 0x0, 0x0, 0x0)
	/var/lib/appuser/worker/go/src/github.com/hashgraph/hedera-sdk-go/query_builder.go:70 +0x43d
github.com/hashgraph/hedera-sdk-go.(*QueryBuilder).execute(0xc0001135a0, 0xc00025a1c0, 0xb93ba0, 0x1, 0xc0000102d0)
	/var/lib/appuser/worker/go/src/github.com/hashgraph/hedera-sdk-go/query_builder.go:135 +0xcf
github.com/hashgraph/hedera-sdk-go.(*AccountBalanceQuery).Execute(0xc0001135a0, 0xc00025a1c0, 0x0, 0x23f09, 0xc0001034c0)
	/var/lib/appuser/worker/go/src/github.com/hashgraph/hedera-sdk-go/account_balance_query.go:51 +0x3b
main.getAccountBalance(0x23f09, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/www/worker.adsongo.com/go/go-worker.go:2741 +0x23a
main.main()
	/var/www/worker.adsongo.com/go/go-worker.go:753 +0x544
exit status 2
```

I've also just reproduced the issue again by checking out commit 71b3622 (add the ability to query a contract balance)

Cheers, Rhys.

**Comment by QuestofIranon** [comment] 2020-02-27 21:02
Hi @rhysied, can you provide some context or an example of what you are doing? I am unable to reproduce this.

**Comment by rhysied** [comment] 2020-02-27 22:07
Hi Josh,

when our worker starts up it makes a balance query to ensure we don't keep attempting to submit transactions which will fail due to insufficient balance.

Line 753 is a call to our `getAccountBalance()` helper function, which runs the following logic:
```
func getAccountBalance(accountID uint64) HederaBalanceStruct {

	client := hederaClient
	client.SetOperator(hedera.AccountID{Account: workerAccountNum}, workerSK)

	balance, err := hedera.
		NewAccountBalanceQuery().
		SetAccountID(hedera.AccountID{Account: accountID}).
		Execute(client)

		//rest of the function
```

When we initially create the client we set the maximum query cost to 1 tinybar as we only make receipt and balance queries (I tried setting it to 0 but that caused an error). I wouldn't have thought that would be the issue as I would expect to see one of the Hedera error codes rather than a segfault.

The stack trace shows that after we call `Execute(client)` on the balance query, everything else takes place within the Go SDK and then the golang/protobuf module. I wouldn't have thought it was an environmental issue as afaik nothing massive has changed in the Go SDK (no version requirement updates, etc, etc) between the commits I've mentioned, and `71b3622` is working fine.


Cheers, Rhys.

**Comment by mehcode** [comment] 2020-02-27 23:01
> I would expect to see one of the Hedera error codes rather than a segfault.

For context, Go isn't remotely null safe ( or "safe" in any defined context ). The segfault is coming from somewhere in the proto lib where it's trying to do `x.y` where `x` is `nil`. It could even be a protobuf lib version difference ( as version requirements are suggestions in Go so it could have updated without us requiring a newer version ).

I haven't tried to repro it yet but I will.

**Comment by mehcode** [comment] 2020-03-26 21:59
@QuestofIranon Can we confirm that this was resolved?

**Comment by mehcode** [comment] 2020-03-27 18:05
I'm going to close this as I can't reproduce this now and we have a large amount of both unit tests and end-to-end tests.

@rhysied When you get a chance, can you check in to see if you can reproduce it still in your environment and re-opening if you can.

**Closed by mehcode** 2020-03-27 18:05 UTC
